name: phototook
description: "Meta search engine for photos on the best image platforms and resources."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:  
  fast_cached_network_image: ^1.2.9
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^5.1.0  
  flutter_markdown: ^0.7.3
  flutter_riverpod: ^2.5.1
  http: ^1.2.1
  intl: ^0.19.0
  path_provider: ^2.1.3  
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/files/
    - assets/fonts/
    - assets/.env
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-ExtraLight.ttf
    - family: MajorMonoDisplay
      fonts:
        - asset: assets/fonts/MajorMonoDisplay-Regular.ttf
